Refactor: pass icon as props to button.
CSCfi/swift-browser-ui pull request #421
Opened 2021-12-03 07:38 UTC by csc-felipe

### Description

Pass icons as props to buttons that didn't yet, so that they position better in relation to the button label. I think it looks better, but it does take up more horizontal space.

Before:
![image](https://user-images.githubusercontent.com/93575941/144563620-1711c574-af78-45c9-8f3c-79b4ae0e9acc.png)
After:
![image](https://user-images.githubusercontent.com/93575941/144563680-62488719-4d70-46ee-9a68-31a537351ee5.png)

### Related issues

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

### Testing

- [x] Tests do not apply

### Mentions

2021-12-03 09:37 UTC, sampsapenna approved these changes

2021-12-03 09:56 UTC, blankdots requested changes
I think we missed a few spots e.g. in ObjectTable lines 257, 268, 278

search in frontend dir `icon=` and see what else can be improved

2021-12-07 10:04 UTC, csc-felipe commented
> I think we missed a few spots e.g. in ObjectTable lines 257, 268, 278
> 
> search in frontend dir `icon=` and see what else can be improved

@blankdots I had already checked those. They are HTML <a> tags, not buefy buttons. Thus the change does not apply.

Or was your suggestions to convert them to buttons?

2021-12-07 10:26 UTC, blankdots commented
> > I think we missed a few spots e.g. in ObjectTable lines 257, 268, 278
> > 
> > search in frontend dir `icon=` and see what else can be improved
> 
> @blankdots I had already checked those. They are HTML `<a>` tags, not buefy buttons. Thus the change does not apply.
> 
> Or was your suggestions to convert them to buttons?

it is fine if they are as <a>

2021-12-07 10:51 UTC, blankdots approved these changes

2021-12-07 10:52 UTC, merged