Feature/create and edit folder
CSCfi/swift-browser-ui pull request #651
Opened 2022-06-27 12:27 UTC by hannyle

### Description

- Implementing a new modal for creating and editing folder based on new UI design: https://www.figma.com/proto/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=526%3A5506&scaling=min-zoom&page-id=517%3A2532&starting-point-node-id=517%3A2533&show-proto-sidebar=1
- Adding possibility to view project members in MyCSC.

### Related issues
Closes https://github.com/CSCfi/swift-browser-ui/issues/612, https://github.com/CSCfi/swift-browser-ui/issues/613

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Removed routes to **add** and **edit** folder
- Added modal from `csc-ui` to create and edit folder
- Added link to MyCSC to see project members
- Updated e2e test
- Modified `path` in `e2etests.yml` file to show screenshots and videos when the tests fail in github

### Testing

- [x] Integration Tests

### Mentions
- I would need help with Finnish translation for new terms used.

2022-06-29 10:06 UTC, saulipurhonen commented
Maybe rebase with `devel` branch so it would be a bit easier to review?

2022-07-01 05:47 UTC, saulipurhonen approved these changes
Looks good to me! Functionality works as described and code formatting has improved from previous version.

2022-07-01 07:09 UTC, saulipurhonen commented
One thing I noticed is that focus isn't trapped inside modal so user is able to navigate behind the modal with keyboard. This however seems to be problem within the CSC DS component library.

2022-07-05 07:30 UTC, sampsapenna requested changes
Added translations for Finnish parts, I can add them myself if necessary. Single line not parameterized. Other than that, LGTM 👍🏼

2022-07-05 07:30 UTC, sampsapenna commented on swift_browser_ui_frontend/src/common/lang.js
> +      tagPlaceholder: "# Add a tag and press enter",
Translation: *Lisää tunniste ja paina rivinvaihtoa*

2022-07-05 07:30 UTC, sampsapenna commented on swift_browser_ui_frontend/src/common/lang.js
> +        myResearchProject: "My research project.",
Translation: *Tutkimusprojektini.*

2022-07-05 07:30 UTC, sampsapenna commented on swift_browser_ui_frontend/src/views/AddContainer.vue
> +        View project members
This is missing internationalisation. Example for Finnish translation: *Näytä projektin jäsenet*

2022-07-08 07:33 UTC, sampsapenna approved these changes

2022-07-08 12:53 UTC, merged